# **Project Overview**

# **Anime Recommendation System**

Building an Anime Recommendation System using Cosine Similarity based on features like:

->Genre

->Rating

->Episodes

->Popularity (members)

This is a content-based filtering system (not collaborative filtering).

In [65]:
# Step 1: Import Libraries
import pandas as pd
import numpy as np

from sklearn.preprocessing import MinMaxScaler
from sklearn.metrics.pairwise import cosine_similarity
from sklearn.feature_extraction.text import CountVectorizer

In [66]:
# Step 2: Load Dataset
df = pd.read_csv("/content/anime.csv")
df.head()

,anime_id,name,genre,type,episodes,rating,members
0,32281,Kimi no Na wa.,"Drama, Romance, School, Supernatural",Movie,1,9.37,200630
1,5114,Fullmetal Alchemist: Brotherhood,"Action, Adventure, Drama, Fantasy, Magic, Mili...",TV,64,9.26,793665
2,28977,Gintama°,"Action, Comedy, Historical, Parody, Samurai, S...",TV,51,9.25,114262
3,9253,Steins;Gate,"Sci-Fi, Thriller",TV,24,9.17,673572
4,9969,Gintama&#039;,"Action, Comedy, Historical, Parody, Samurai, S...",TV,51,9.16,151266

In [67]:
df

,anime_id,name,genre,type,episodes,rating,members
0,32281,Kimi no Na wa.,"Drama, Romance, School, Supernatural",Movie,1,9.37,200630
1,5114,Fullmetal Alchemist: Brotherhood,"Action, Adventure, Drama, Fantasy, Magic, Mili...",TV,64,9.26,793665
2,28977,Gintama°,"Action, Comedy, Historical, Parody, Samurai, S...",TV,51,9.25,114262
3,9253,Steins;Gate,"Sci-Fi, Thriller",TV,24,9.17,673572
4,9969,Gintama&#039;,"Action, Comedy, Historical, Parody, Samurai, S...",TV,51,9.16,151266
...,...,...,...,...,...,...,...
12289,9316,Toushindai My Lover: Minami tai Mecha-Minami,Hentai,OVA,1,4.15,211
12290,5543,Under World,Hentai,OVA,1,4.28,183
12291,5621,Violence Gekiga David no Hoshi,Hentai,OVA,4,4.88,219
12292,6133,Violence Gekiga Shin David no Hoshi: Inma Dens...,Hentai,OVA,1,4.98,175
12293,26081,Yasuji no Pornorama: Yacchimae!!,Hentai,Movie,1,5.46,142

In [68]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 12294 entries, 0 to 12293
Data columns (total 7 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   anime_id  12294 non-null  int64
 1   name      12294 non-null  object
 2   genre     12232 non-null  object
 3   type      12269 non-null  object
 4   episodes  12294 non-null  object
 5   rating    12064 non-null  float64
 6   members   12294 non-null  int64
dtypes: float64(1), int64(2), object(4)
memory usage: 672.5+ KB

In [69]:
df.isnull().sum()

anime_id      0
name          0
genre        62
type         25
episodes      0
rating      230
members       0
dtype: int64

In [70]:
print(df.describe())
print(df['genre'].head())

           anime_id        rating       members
count  12294.000000  12064.000000  1.229400e+04
mean   14058.221653      6.473902  1.807134e+04
std    11455.294701      1.026746  5.482068e+04
min        1.000000      1.670000  5.000000e+00
25%     3484.250000      5.880000  2.250000e+02
50%    10260.500000      6.570000  1.550000e+03
75%    24794.500000      7.180000  9.437000e+03
max    34527.000000     10.000000  1.013917e+06
0                 Drama, Romance, School, Supernatural
1    Action, Adventure, Drama, Fantasy, Magic, Mili...
2    Action, Comedy, Historical, Parody, Samurai, S...
3                                     Sci-Fi, Thriller
4    Action, Comedy, Historical, Parody, Samurai, S...
Name: genre, dtype: object

In [74]:
print(df[['rating', 'episodes', 'members']].isnull().sum())

rating      0
episodes    0
members     0
dtype: int64

In [78]:
# Step 3: Data Preprocessing
# Handle missing values
df['genre'] = df['genre'].fillna('')
df['rating'] = df['rating'].fillna(df['rating'].mean())

df['episodes'] = df['episodes'].replace('Unknown', np.nan)
# Convert types before calculating median or filling NaN
df['episodes'] = df['episodes'].astype(float)
df['episodes'] = df['episodes'].fillna(df['episodes'].median())

df['members'] = df['members'].fillna(df['members'].median())


# Step 4: Feature Extraction
# Vectorize genre
from sklearn.feature_extraction.text import CountVectorizer
cv = CountVectorizer(tokenizer=lambda x: x.split(','), token_pattern=None)
genre_matrix = cv.fit_transform(df['genre'])

# Normalize numerical features
from sklearn.preprocessing import MinMaxScaler
scaler = MinMaxScaler()
num_features = scaler.fit_transform(df[['rating', 'episodes', 'members']])

# Combine
from scipy.sparse import hstack
feature_matrix = hstack([genre_matrix, num_features])

# Step:5 Compute Cosine Similarity

from sklearn.metrics.pairwise import cosine_similarity
cosine_sim = cosine_similarity(feature_matrix)

In [84]:
# Step 6: Recommendation Function
def recommend_anime(title, n=10):
    idx = df[df['name'] == title].index[0]

    sim_scores = list(enumerate(cosine_sim[idx]))
    sim_scores = sorted(sim_scores, key=lambda x: x[1], reverse=True)[1:n+1]

    anime_indices = [i[0] for i in sim_scores]

    return df['name'].iloc[anime_indices].values

In [85]:
print(recommend_anime("Naruto"))

['Naruto: Shippuuden' 'Naruto: Shippuuden Movie 4 - The Lost Tower'
 'Naruto: Shippuuden Movie 3 - Hi no Ishi wo Tsugu Mono'
 'Boruto: Naruto the Movie' 'Naruto x UT'
 'Naruto Soyokazeden Movie: Naruto to Mashin to Mitsu no Onegai Dattebayo!!'
 'Boruto: Naruto the Movie - Naruto ga Hokage ni Natta Hi'
 'Naruto Shippuuden: Sunny Side Battle' 'Katekyo Hitman Reborn!'
 'Kyutai Panic Adventure!']

In [91]:
# Step 7: Threshold-Based Recommendations
def recommend_with_threshold(title, threshold=0.5):
    idx = df[df['name'] == title].index[0]

    sim_scores = list(enumerate(cosine_sim[idx]))

    filtered = [i for i in sim_scores if i[1] > threshold]

    filtered = sorted(filtered, key=lambda x: x[1], reverse=True)

    anime_indices = [i[0] for i in filtered[1:]]

    return df['name'].iloc[anime_indices]

In [94]:
for anime in recommend_with_threshold("Naruto", 0.6):
    print(anime)

Naruto: Shippuuden
Naruto: Shippuuden Movie 4 - The Lost Tower
Naruto: Shippuuden Movie 3 - Hi no Ishi wo Tsugu Mono
Boruto: Naruto the Movie
Naruto x UT
Naruto Soyokazeden Movie: Naruto to Mashin to Mitsu no Onegai Dattebayo!!
Boruto: Naruto the Movie - Naruto ga Hokage ni Natta Hi
Naruto Shippuuden: Sunny Side Battle
Katekyo Hitman Reborn!
Kyutai Panic Adventure!
Battle Spirits: Ryuuko no Ken
Dragon Ball Z
Dragon Ball Kai
Bleach
Dragon Ball Super
Medaka Box
Tenjou Tenge
Medaka Box Abnormal
Dragon Ball Kai (2014)
Dragon Ball Z Movie 15: Fukkatsu no F
Dragon Ball GT: Goku Gaiden! Yuuki no Akashi wa Suushinchuu
Dragon Ball Z Movie 11: Super Senshi Gekiha!! Katsu no wa Ore da
Dragon Ball Z: Summer Vacation Special
Dragon Ball Z: Atsumare! Gokuu World
Boku no Hero Academia
Shijou Saikyou no Deshi Kenichi
Bleach Movie 3: Fade to Black - Kimi no Na wo Yobu
Bleach Movie 4: Jigoku-hen
Naruto: Shippuuden Movie 6 - Road to Ninja
The Last: Naruto the Movie
Shijou Saikyou no Deshi Kenichi OVA
Rekka no Honoo
Naruto: Takigakure no Shitou - Ore ga Eiyuu Dattebayo!
Naruto: Honoo no Chuunin Shiken! Naruto vs. Konohamaru!!
One Piece: Romance Dawn Story
Ranma ½: Akumu! Shunmin Kou
Boku no Hero Academia: Jump Festa 2016 Special
One Piece: Romance Dawn
Sakigake!! Otokojuku
Boku no Hero Academia 2nd Season
Ben-To
Muteki Kanban Musume
Shijou Saikyou no Deshi Kenichi Specials
Kenyuu Densetsu Yaiba
Virtua Fighter
Toriko: Jump Super Anime Tour 2009 Special
Kakutou Bijin Wulong: Rebirth
Yuu☆Yuu☆Hakusho Picture Drama
Street Fighter Zero The Animation
Toriko: Barbarian Ivy wo Hokaku Seyo!
Sakigake!! Otokojuku Movie
Crayon Shin-chan Manatsu no Yoru ni Ora Sanjou! Arashi wo Yobu Den-O vs. Shin-O 60-bu Special!!
Tatakae!! Ramenman
Getsumen To Heiki Mina Specials
Ninku: Knife no Bohyou
Variable Geo
Kurokami The Animation
Dragon Ball Z Movie 10: Kiken na Futari! Super Senshi wa Nemurenai
Dragon Ball: Episode of Bardock
Big Order (TV)
Ansatsu Kyoushitsu
Dragon Ball Z: Zenbu Misemasu Toshi Wasure Dragon Ball Z!
Street Fighter II: The Movie
Black Cat Special
Iron Virgin Jun
Aoharu x Kikanjuu: Kemono-tachi no Senjou da na!
Project ARMS
Kurokami: Tora to Tsubasa
Baki
Koukou Tekken-den Tough
Kurokami: Intermission
Wolverine
Big Order
Shounan Bakusouzoku
Lupin III: Pilot Film
Tiger &amp; Bunny Pilot
Akai Hayate
Abashiri Ikka
Kyutai Panic Adventure Returns!
Huang Feihong Yong Chuang Tianxia
Dragon Ball
Code:Breaker
Naruto: Shippuuden Movie 5 - Blood Prison
Saint Seiya: The Lost Canvas - Meiou Shinwa
Dragon Ball Z Movie 14: Kami to Kami
Yozakura Quartet: Hana no Uta
Saint Seiya: The Lost Canvas - Meiou Shinwa 2
One Piece Film: Strong World Episode 0
One Piece Movie 4: Dead End no Bouken
Tokyo ESP
Yozakura Quartet
One Piece: Episode of Luffy - Hand Island no Bouken
One Piece Movie 9: Episode of Chopper Plus - Fuyu ni Saku, Kiseki no Sakura
One Piece Movie 1
One Piece Movie 5: Norowareta Seiken
One Piece Movie 2: Nejimaki-jima no Daibouken
Dragon Ball Kai: Mirai ni Heiwa wo! Goku no Tamashii yo Eien ni
One Piece Movie 3: Chinjuu-jima no Chopper Oukoku
Yozakura Quartet: Hoshi no Umi
Naruto: Dai Katsugeki!! Yuki Hime Shinobu Houjou Dattebayo! Special: Konoha Annual Sports Festival
Taboo Tattoo
Yozakura Quartet: Tsuki ni Naku
One Piece: Umi no Heso no Daibouken-hen
One Piece: Oounabara ni Hirake! Dekkai Dekkai Chichi no Yume!
Kill la Kill
One Piece: Adventure of Nebulandia
Ranma ½: Chou Musabetsu Kessen! Ranma Team vs. Densetsu no Houou
Dragon Ball Movie 1: Shen Long no Densetsu
One Piece: Glorious Island
One Piece Recap
Kyattou Ninden Teyandee
Hunter x Hunter (2011)
One Piece: Taose! Kaizoku Ganzack
Kinnikuman II Sei
One Piece Film: Gold Episode 0 - 711 ver.
Kinnikuman II Sei: Ultimate Muscle 2
Kinnikuman II Sei: Ultimate Muscle
Gatchaman
One Piece
Baoh Raihousha
Ninku (Movie)
D.Gray-man
Ansatsu Kyoushitsu (TV)
Ansatsu Kyoushitsu (TV) 2nd Season
Hunter x Hunter
Yuu☆Yuu☆Hakusho
Tiger &amp; Bunny
Eyeshield 21
Naruto: Shippuuden Movie 2 - Kizuna
Kill la Kill Special
Aoharu x Kikanjuu
D.Gray-man Hallow
Hunter x Hunter: Greed Island Final
Hunter x Hunter: Greed Island
Hunter x Hunter OVA
Lupin III
Prince of Tennis: The National Tournament
Hunter x Hunter Movie: Phantom Rouge
City Hunter
GetBackers
New Prince of Tennis
Lupin III: Part II
Lupin III (2015)
Hunter x Hunter Movie: The Last Mission
City Hunter 2
Saint Seiya: Meiou Hades Elysion-hen
Zettai Karen Children
Tiger &amp; Bunny Movie 2: The Rising
Lupin III vs. Detective Conan: The Movie
Ansatsu Kyoushitsu (TV): Deai no Jikan
Shin Mazinger Shougeki! Z-hen
Ansatsu Kyoushitsu: 365-nichi no Jikan
City Hunter 3
Ansatsu Kyoushitsu (TV) 2nd Season: Kagaijugyou-hen
One Piece: Episode of Nami - Koukaishi no Namida to Nakama no Kizuna
City Hunter &#039;91
Hokuto no Ken 2
Chuuka Ichiban!
One Piece: Episode of Merry - Mou Hitori no Nakama no Monogatari
Kamen no Maid Guy
Tiger &amp; Bunny Movie 1: The Beginning
Grappler Baki: Saidai Tournament-hen
New Prince of Tennis OVA vs. Genius10
Air Master
Lupin III: Part III
New Prince of Tennis Specials
Shaman King Specials
Taiho Shichau zo: Second Season
Ganbare Genki
City Hunter: Ai to Shukumei no Magnum
Hunter x Hunter Pilot
City Hunter: The Secret Service
City Hunter: Hyakuman Dollar no Inbou
Tetsuwan Birdy
Lupin III: Kutabare! Nostradamus
City Hunter: Bay City Wars
Mushibugyou
Naruto: The Cross Roads
Yokohama Bakkure-tai
Taiho Shichau zo: Full Throttle
Lupin III: Fuuma Ichizoku no Inbou
Zettai Karen Children OVA: Aitazousei! Ubawareta Mirai?
Senyuu. Specials
Lupin III: Dead or Alive
Lupin III: Chi no Kokuin - Eien no Mermaid
Lupin III: $1 Money Wars
Lupin III: Nusumareta Lupin
Lupin III (2015) Specials
Lupin III: Alcatraz Connection
Kiddy GiRL-AND
Lupin III: Tenshi no Tactics - Yume no Kakera wa Koroshi no Kaori
Lupin III: Moeyo Zantetsuken!
Taiho Shichau zo Special
One Piece: Episode of Sabo - 3 Kyoudai no Kizuna Kiseki no Saikai to Uketsugareru Ishi
Lupin III: Seven Days Rhapsody
Lupin III: Twilight Gemini no Himitsu
Lupin III: Harimao no Zaihou wo Oe!!
Nano Invaders
Shin Hokuto no Ken
Rurouni Kenshin: Review Special
Kinnikuman: Kinnikusei Oui Soudatsu-hen
Prince of Tennis: Oshougatsu Special
Lupin III: Princess of the Breeze - Kakusareta Kuuchuu Toshi
Viewtiful Joe
Lupin III: Lupin Ansatsu Shirei
Lupin III: Kiri no Elusive
Lupin III: Ai no Da Capo - Fujiko&#039;s Unlucky Days
Lupin III: Bye Bye Liberty - Kiki Ippatsu!
Shingeki no Kyojin
Dragon Ball Movie 4: Saikyou e no Michi
Lupin III: Napoleon no Jisho wo Ubae
Zettai Karen Children Gentei Kaikin!! OVA Chou Sakidori Special!!
Lupin III: Russia yori Ai wo Komete
Sasuke
Eyeshield 21: Jump Festa 2005 Special
Toriko 3D: Kaimaku Gourmet Adventure!!
Duel Masters Cross
Lupin III: Babylon no Ougon Densetsu
Lupin III: Green vs. Red
Lupin III (2015): Italian Game
Chikyuu Bouei Kazoku
Dragon Ball Movie 3: Makafushigi Daibouken
Taiho Shichau zo in America
Dragon Ball Movie 2: Majinjou no Nemuri Hime
Zettai Karen Children Recap
Kinnikuman (1984)
Duel Masters Cross Shock
Kinnikuman: Kessen! Shichinin no Seigi Choujin vs. Uchuu Nobushi
Souten no Ken Specials
Mushibugyou OVA
Kinnikuman: Ooabare! Seigi Choujin
Duel Masters Charge
Onikirimaru
Code:Breaker OVA
Duel Masters Victory
Kinnikuman: Seigi Choujin vs. Kodai Choujin
Duel Masters Victory V
Kinnikuman: New York Kiki Ippatsu!
Kinnikuman: Gyakushuu! Uchuu Kakure Choujin
Duel Masters Movie 2: Lunatic God Saga
Udauda Yatteru Hima wa Nee!
Duel Masters VS
Tiger &amp; Bunny Recaps
Duel Masters Victory V3
Kinnikuman: Haresugata! Seigi Choujin
Kamen Rider Fourze x Crayon Shin-chan
Riki-Oh: Toukatsu Jigoku
Machine Robo: Leina, The Legend of Wolf Blade
Street Fighter II: Yomigaeru Fujiwara-Kyou - Toki wo Kaketa Fighter-tachi
Kinnikuman: Seigi Choujin vs. Senshi Choujin
Duel Masters
Shin Hurricane Polymar
Honoo no Tenkousei
Tiger &amp; Bunny: Too Many Cooks Spoil the Broth
Fight Da!! Pyuta
Tatakae!! Ramenman (Movie)
Gakuen Tokusou Hikaruon
Sexy Sailor Soldiers
Psychic Force
Riki-Oh 2: Horobi no Ko
Mirai Kara Kita Shounen Super Jetter
Duel Masters VSR
Ultraman Graffiti
Duel Masters VSRF
Arcade Gamer Fubuki
Yuu☆Yuu☆Hakusho: Meikai Shitou-hen - Honoo no Kizuna
Kure-nai OVA
Hokuto no Ken: Toki-den
Battle Spirits: Brave
Duel Masters: Hamukatsu to Dogiragon no Curry-pan Daibouken
Hulu Xiongdi
Battle Spirits: Sword Eyes
Aachi wa Ssipak
Naniwa Yuukyouden: Chou Gokudou! Yoru no Bat wa Manrui-hen
Nekojiru Gekijou Jirujiru Original
Naniwa Yuukyouden: Kyouretsu! Ana ga Attara Iretai-hen
Battle Spirits: Heroes
Naniwa Yuukyouden: Nekketsu!! Bakushou Mankai-hen
Naniwa Yuukyouden: Kanketsu-hen
Kara no Kyoukai: Manner Movies
Double Hard
MonHun Nikki Girigiri Airou Mura G
THE REFLECTION
MonHun Nikki Girigiri Airou Mura: Airou Kiki Ippatsu
Ushio to Tora: Comically Deformed Theater
Dragon Ball GT
Hokuto no Ken: Legend of Heroes
Chokin Senshi Cashman
MonHun Nikki Girigiri Airou Mura: Airou Kiki Ippatsu Specials
Inferno Cop Specials
Toumei Shounen Tantei Akira
Naniwa Yuukyouden
Nanbo no Monjai! Yankee Gurentai
Katsura Hime
Heungnyongwanggwa Bihodongja
Taegeugsonyeon Huin Dogsuli
Shin Karate Jigoku-hen
Arisa☆Good Luck
Shinken Densetsu: Tight Road
Geori-eui Mubeopja
Toushinden
Benkei tai Ushiwaka
Pepsi Nex x 009 Re:Cyborg
Zoku Naniwa Yuukyouden
Nanbo no Monjai! 2: Yankee Gurentai
Tough Guy!
Youkai Ninpouchou Jiraiya! Special
Feng Ji Yun Nu
Air Gear
Teppen
Sekirei
Black Cat
Tenkai Knights
Tondemo Senshi Muteking
Shingeki no Kyojin OVA
Prince of Tennis
Chiisana Kyojin Microman
Sekirei: Pure Engagement
Naruto: Shippuuden Movie 1
Shingeki no Kyojin Season 2
Sengoku Basara
Needless
Majin Sentai Death Ranger: Ubawareta Pudding!
Yu☆Gi☆Oh!
Toriko
Hokuto no Ken
Yu☆Gi☆Oh!: Duel Monsters GX
Mahou Shoujo Lyrical Nanoha A&#039;s
Mahou Shoujo Lyrical Nanoha
Senyuu.
Sengoku Basara Two
Air Gear: Kuro no Hane to Nemuri no Mori - Break on the Sky
Mahou Shoujo Lyrical Nanoha: The Movie 2nd A&#039;s
Black Clover
Mahou Shoujo Lyrical Nanoha StrikerS
Cuticle Tantei Inaba
Mahou Shoujo Lyrical Nanoha: The Movie 1st
Shingeki no Kyojin Movie 1: Guren no Yumiya
Tenchi Muyou! Ryououki
Shingeki no Kyojin Movie 2: Jiyuu no Tsubasa
Senyuu. 2
Giant Robo the Animation: Chikyuu ga Seishi Suru Hi
Lupin III vs. Detective Conan
Peace Maker Kurogane
MÄR
Sengoku Basara Movie: The Last Party
Fairy Tail
Mutsu Enmei Ryuu Gaiden: Shura no Toki
Soul Eater NOT!
Shingeki no Kyojin: Ano Hi Kara
Lupin III: Episode 0 &quot;First Contact&quot;
Ikkitousen: Dragon Destiny
One Piece 3D: Mugiwara Chase
Soul Eater
Prince of Tennis: Eikokushiki Teikyuu Shiro Kessen!
Digimon Xros Wars: Aku no Death General to Nanatsu no Oukoku
Ikkitousen: Great Guardians
Yuu☆Yuu☆Hakusho: Eizou Hakusho II
Tobe! Isami
Lupin III: Walther P-38
One Piece 3D: Gekisou! Trap Coaster
Grenadier: Hohoemi no Senshi
Tekken Chinmi
Digimon Xros Wars
Taiho Shichau zo The Movie
Ikkitousen: Xtreme Xecutor
Hitsugi no Chaika OVA
Tenchi Muyou! Manatsu no Eve
Lupin III: Honoo no Kioku - Tokyo Crisis
Kaibutsu Oujo (OVA)
Project ARMS: The 2nd Chapter
Kämpfer für die Liebe
Sengoku Basara: Judge End
Toaru Majutsu no Index 10th Anniversary PV
Scryed Alteration I: Tao
Lupin III: Lupin vs. Fukusei-ningen
Detective Conan: Happy New Year Special
Lupin III: Hemingway Paper no Nazo
Bakuretsu Tenshi: Infinity
Scryed Alteration II: Quan
Lupin III: Touhou Kenbunroku - Another Page
Jinzou Konchuu Kabutoborg VxV
Ikkitousen: Shuugaku Toushi Keppuuroku
Fatal Fury 2: The New Battle
Eat-Man &#039;98
Juubee-chan: Lovely Gantai no Himitsu
Digimon Xros Wars: Toki wo Kakeru Shounen Hunter-tachi
Kamen Rider Den-O: Imagin Anime 2
Yume Senshi Wingman
Hareluya II Boy
Digimon Savers the Movie: Kyuukyoku Power! Burst Mode Hatsudou!!
Kamen Rider Den-O: Imagin Anime
Eat-Man
Project A-Ko 2: Daitokuji Zaibatsu no Inbou
Beast Wars Neo
Aozora Shoujo-tai
Project A-Ko 4: Final
Project A-Ko 3: Cinderella Rhapsody
Choujuushin Gravion
The Ultraman
Kamen Rider Den-O: Imagin Anime 3
Ultraman: Chou Toushi Gekiden - Suisei Senjin Tsuifon Toujou
Bobobo-bo Bo-bobo Recap
Yumeria
Mahou Shoujo Lyrical Nanoha Reflection
Peace Maker Kurogane (Shinsaku)
Tetsuwan Atom: Ivan no Wakusei - Robot to Ningen no Yuujou
Kenritsu Chikyuu Boueigun
Bakuen Campus Guardress
Mouse
Samurai Spirits 2: Asura Zanmaden
Samurai Champloo
Sacred Seven: Shirogane no Tsubasa Picture Drama
Ogami Matsugorou
Shibai Taroka
Magma Taishi